<#
Noise Survey Analysis - Setup
=============================

Run this once on a new computer. It:
  * finds or installs Python
  * builds a private Python environment and installs the packages
  * checks VLC (needed only for audio playback)
  * adds a desktop shortcut and the Explorer right-click menus

The application itself is not copied anywhere - it runs from the shared drive,
which Google Drive keeps synced on every machine.

It is safe to run again at any time. Use -Force to rebuild from scratch if
something has gone wrong.

Usage: right-click and choose "Run with PowerShell", or double-click
       setup_noise_survey.bat
#>

[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$NoShortcut
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '_lib\nsa-common.ps1')

# ---------------------------------------------------------------------------
# Explorer integration
# ---------------------------------------------------------------------------

function Remove-NsaContextMenus {
    # Old and current registration points. Cleaning HKCR entries too, because
    # early versions of this tool wrote there and left machines with stale
    # commands pointing at paths that no longer exist.
    $keys = @(
        'HKCU\Software\Classes\SystemFileAssociations\.svl\shell\ExtractTHData',
        'HKCU\Software\Classes\SystemFileAssociations\.svn\shell\ExtractTHData',
        'HKCU\Software\Classes\SystemFileAssociations\.csv\shell\ExtractTHData',
        'HKCU\Software\Classes\SystemFileAssociations\.xls\shell\ExtractTHData',
        'HKCU\Software\Classes\SystemFileAssociations\.xlsx\shell\ExtractTHData',
        'HKCU\Software\Classes\SystemFileAssociations\.json\shell\OpenNoiseSurvey',
        'HKCR\Directory\Background\shell\ExtractTHData',
        'HKCR\Svan.File\shell\ExtractTHData',
        'HKCR\*\shell\ExtractTHData',
        'HKCR\SystemFileAssociations\.svl\shell\ExtractTHData',
        'HKCR\SystemFileAssociations\.svn\shell\ExtractTHData',
        'HKCR\SystemFileAssociations\.csv\shell\ExtractTHData',
        'HKCR\SystemFileAssociations\.xls\shell\ExtractTHData',
        'HKCR\SystemFileAssociations\.xlsx\shell\ExtractTHData'
    )
    foreach ($key in $keys) {
        try { & reg.exe delete $key /f 2>$null | Out-Null } catch { }
    }
}

function Install-NsaSlmContextMenu {
    <#
      Registers "Extract TH data" on meter files.

      The command goes through a small .bat in LocalAppData rather than calling
      python.exe directly. Google Drive File Stream does not provide 8.3 short
      paths, so the shared-drive path (which contains spaces) cannot be quoted
      reliably inside a registry command string. Bouncing through a local
      launcher with no spaces in its own path avoids that entirely.
    #>
    param([string]$SlmRoot, [string]$VenvPython, [string]$InstallRoot)

    $processScript = Join-Path $SlmRoot 'src\process_files.py'
    if (-not (Test-Path $processScript)) {
        Write-NsaWarn "SLM parser not found at $processScript - skipping the 'Extract TH data' menu."
        return
    }

    $launcher = Join-Path $InstallRoot 'extract_th_launcher.bat'
    $content = @"
@echo off
REM Generated by setup_noise_survey.ps1 - do not edit by hand.
echo Processing: %~1
echo.
"$VenvPython" "$processScript" "%~1"
echo.
pause
"@
    Set-Content -Path $launcher -Value $content -Encoding ASCII

    $command = 'cmd.exe /c ""' + $launcher + '" "%1""'
    foreach ($ext in @('.svl', '.svn', '.csv', '.xls', '.xlsx')) {
        $regPath = "HKCU:\Software\Classes\SystemFileAssociations\$ext\shell\ExtractTHData"
        if (-not (Test-Path $regPath)) { New-Item -Path $regPath -Force | Out-Null }
        Set-ItemProperty -Path $regPath -Name '(Default)' -Value 'Extract TH data'
        $commandPath = Join-Path $regPath 'command'
        if (-not (Test-Path $commandPath)) { New-Item -Path $commandPath -Force | Out-Null }
        Set-ItemProperty -Path $commandPath -Name '(Default)' -Value $command
    }
    Write-NsaOk 'Right-click "Extract TH data" registered for .svl .svn .csv .xls .xlsx files.'
}

function Install-NsaDashboardContextMenu {
    param([string]$LaunchScript)

    if (-not (Test-Path $LaunchScript)) {
        Write-NsaWarn "Launch script not found at $LaunchScript - skipping the .json right-click menu."
        return
    }
    $command = 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"{0}\" -ConfigPath \"%1\"' -f $LaunchScript
    $baseKey = 'HKCU\Software\Classes\SystemFileAssociations\.json\shell\OpenNoiseSurvey'
    & reg.exe add $baseKey /ve /d 'Open in Noise Survey Analysis' /f | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-NsaWarn 'Could not register the .json right-click menu.'; return }
    & reg.exe add "$baseKey\command" /ve /d $command /f | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-NsaWarn 'Could not register the .json right-click command.'; return }
    Write-NsaOk 'Right-click "Open in Noise Survey Analysis" registered for .json config files.'
}

function Remove-NsaLegacyEnvironments {
    <#
      Earlier versions kept the virtual environment in a folder named after a
      SHA1 of the shared path, so every machine that ran the old setup is
      sitting on a couple of hundred megabytes of dead environment per install.
      They are this tool's own leftovers and nothing else refers to them.
    #>
    param([string]$InstallRoot)

    $legacy = @(Get-ChildItem -Path $InstallRoot -Directory -ErrorAction SilentlyContinue |
                Where-Object { $_.Name -match '^[0-9a-f]{40}$' })
    if ($legacy.Count -eq 0) { return }

    $freed = 0
    foreach ($dir in $legacy) {
        $bytes = (Get-ChildItem -Path $dir.FullName -Recurse -File -Force -ErrorAction SilentlyContinue |
                  Measure-Object Length -Sum).Sum
        Remove-Item -Path $dir.FullName -Recurse -Force -ErrorAction SilentlyContinue
        if (-not (Test-Path $dir.FullName)) { $freed += $bytes }
    }
    if ($freed -gt 0) {
        Write-NsaOk ("Removed {0} old environment(s) left by a previous version ({1} MB reclaimed)." -f $legacy.Count, [math]::Round($freed / 1MB))
    }
}

function Install-NsaShortcut {
    param([string]$ShareRoot)
    $desktop = [Environment]::GetFolderPath('Desktop')
    if (-not (Test-Path $desktop)) { Write-NsaWarn 'Desktop folder not found - skipping shortcut.'; return }

    $target = Join-Path $ShareRoot 'launch_noise_survey.bat'
    if (-not (Test-Path $target)) { Write-NsaWarn "Launcher not found at $target - skipping shortcut."; return }

    $shortcutPath = Join-Path $desktop 'Noise Survey Analysis.lnk'
    $shell = New-Object -ComObject WScript.Shell
    $shortcut = $shell.CreateShortcut($shortcutPath)
    $shortcut.TargetPath = $target
    $shortcut.WorkingDirectory = $ShareRoot
    $shortcut.Description = 'Launch the Noise Survey Analysis dashboard'
    $shortcut.Save()
    Write-NsaOk "Desktop shortcut created: $shortcutPath"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

try {
    $paths = Get-NsaPaths -ShareRoot $PSScriptRoot
    $log = Start-NsaLog -Name 'setup'

    Write-NsaSection 'Noise Survey Analysis - Setup'
    Write-NsaInfo "Shared folder : $($paths.ShareRoot)"
    Write-NsaInfo "Installing to : $($paths.InstallRoot)"
    Write-NsaInfo "Log file      : $log"

    if (-not (Test-Path $paths.SharePayload)) {
        throw "Application folder not found at $($paths.SharePayload). Check that Google Drive is running and you have access to the Venta shared drive."
    }

    $result = Invoke-NsaEnsureReady -Paths $paths -Force:$Force -AllowVlcInstall
    if (-not $result.Ready) {
        Write-NsaSection 'Setup did not complete'
        Write-NsaInfo "Send this log file to Steve: $log"
        Wait-NsaForUser
        exit 1
    }

    Remove-NsaLegacyEnvironments -InstallRoot $paths.InstallRoot

    Write-NsaSection 'Explorer and desktop integration'
    Remove-NsaContextMenus
    if (Test-Path $paths.ShareSlm) {
        Install-NsaSlmContextMenu -SlmRoot $paths.ShareSlm -VenvPython $paths.VenvPython -InstallRoot $paths.InstallRoot
    } else {
        Write-NsaInfo "No 'SLM Parsers' folder on the shared drive - skipping the meter-file menu."
    }
    Install-NsaDashboardContextMenu -LaunchScript (Join-Path $paths.ShareRoot 'launch_noise_survey.ps1')
    if (-not $NoShortcut) { Install-NsaShortcut -ShareRoot $paths.ShareRoot }

    Write-NsaSection 'Setup complete'
    Write-NsaLine '  You are ready to go. From now on you only need the desktop shortcut -' 'Green'
    Write-NsaLine '  it updates itself automatically when Steve releases a new version.' 'Green'
    Write-NsaLine ''
    Write-NsaInfo 'To open a survey:'
    Write-NsaInfo '  * double-click the "Noise Survey Analysis" desktop shortcut, or'
    Write-NsaInfo '  * right-click a noise_survey_config_XXXX.json file and choose'
    Write-NsaInfo '    "Open in Noise Survey Analysis"'
    Write-NsaInfo ''
    Write-NsaInfo 'If anything goes wrong, run diagnose_noise_survey.bat and send Steve the report.'

} catch {
    Write-NsaLine ''
    Write-NsaFail $_.Exception.Message
    if (Get-NsaLogFile) { Write-NsaInfo "Send this log file to Steve: $(Get-NsaLogFile)" }
    Wait-NsaForUser
    exit 1
}

Wait-NsaForUser
